---
title: "Docker"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

To run LakeEnsemblR (coupled with example files and workshop instructions), you can also use a [container](https://hub.docker.com/r/hydrobert/lakeensemblr-rocker) of all the material. We'll quote the Docker website here to define what a container is: 
  > "A container is a standard unit of software that packages up code and all its dependencies so the application runs quickly and reliably from one computing environment to another. A Docker container image is a lightweight, standalone, executable package of software that includes everything needed to run an application: code, runtime, system tools, system libraries and settings." 
  
  You can install the Docker software from [here](https://docs.docker.com/get-docker/). Once installed, you'll need to open a terminal and type (the pulling will take some time depending on your internet connection, it's about 4 Gb big)
  ```
  docker pull hydrobert/lakeensemblr-rocker
  docker run --rm -d  -p 8000:8000 -e ROOT=TRUE -e PASSWORD=password hydrobert/lakeensemblr-rocker:latest
  ```
  Then, open any web browser and type "localhost:8000" and input user: rstudio, and password: password. Rstudio will open up with the script and data available in the file window. 



You can modify files here and also link input as well as output data to your local volumes. 

**Using docker will ensure that the LakeEnsemblR software will work on your machine regardless of your OS, R or RStudio configuration.**
