---
title: "Setting up LakeEnsemblR"
editor_options: 
  markdown: 
    wrap: 100
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction

A key part of developing LakeEnsemblR was to develop a standardised format for model input data.
This involved standard variable naming which includes units.

## DateTime formatting

This package uses international standard format for date and time (ISO 8601), which is
`YYYY-mm-dd HH:MM:SS`. For example: `2020-04-03 09:00:00`.

## Time Zones

Currently this is not accounted for so the timezone used in input is the timezone of output data. It
is on the list of things to do.

## Hypsograph data

The data needs to be a comma separated values (.csv) file where 0m is the surface and all depths are
reported as positive. Area needs to be in meters squared. The column names *must* be `Depth_meter`
and `Area_meterSquared`

Example of data:

```         
Depth_meter,Area_meterSquared
0,3931000
1,3688025
2,3445050
3,3336093.492
4,3225992.455
5,3133491.11
6,3029720
...
```

## Temperature Profile data

The data needs to be a comma separated values (.csv) file where the datetime column is in the format
`YYYY-mm-dd HH:MM:SS`. Depths are positive and relative to the water surface. Water temperature is
in degrees Celsius. The column names *must* be `datetime`, `Depth_meter` and
`Water_Temperature_celsius`

Example of data:

```         
datetime,Depth_meter,Water_Temperature_celsius
2004-01-05 00:00:00,0.9,6.97
2004-01-05 00:00:00,2.5,6.71
2004-01-05 00:00:00,5,6.73
2004-01-05 00:00:00,8,6.76
...
```

## Meteorological data

The data needs to be a comma separated values (.csv) file where the datetime column is in the format
`YYYY-mm-dd HH:MM:SS`. See table 1 for the list of variables, units and column names.

| Description | Units | Column Name | Status |
|----------------|----------------|----------------|-----------------------------------------------------|
| Downwelling longwave radiation | W/m2 | Longwave_Radiation_Downwelling_wattPerMeterSquared | If not provided,it is calculated internally from air temperature, cloud cover and relative humidity/dewpoint temperature |
| Downwelling shortwave radiation | W/m2 | Shortwave_Radiation_Downwelling_wattPerMeterSquared | Required |
| Cloud cover | \- | Cloud_Cover_decimalFraction | If not provided,it is calculated internally from air temperature, short-wave radiation, latitude, longitude, elevation and relative humidity/dewpoint temperature |
| Air temperature | 째C | Air_Temperature_celsius | Required |
| Relative humidity | \% | Relative_Humidity_percent | If not provided,it is calculated internally from air temperature and dewpoint temperature |
| Dewpoint temperature | 째C | Dewpoint_Temperature_celsius | If not provided,it is calculated internally from air temperature and relative humidity |
| Wind speed at 10m | m/s | Ten_Meter_Elevation_Wind_Speed_meterPerSecond | Either wind speed or u and v vectors is required |
| Wind direction at 10m | 째C | Ten_Meter_Elevation_Wind_Direction_degree | Not required, but if provided u and v vectors are calculated internally |
| Wind u-vector at 10m | m/s | Ten_Meter_Uwind_vector_meterPerSecond | Either wind speed or u and v vectors is required |
| Wind v-vector at 10m | m/s | Ten_Meter_Vwind_vector_meterPerSecond | Either wind speed or u and v vectors is required |
| Precipitation | mm/hr or mm/day | Precipitation_millimeterPerHour or Precipitation_millimeterPerDay | Not strictly required but is important for mass budgets in some models |
| Rainfall | mm/hr or mm/day | Rainfall_millimeterPerHour or Rainfall_millimeterPerDay | Required |
| Snowfall | mm/hr or mm/day | Snowfall_millimeterPerHour or Snowfall_millimeterPerDay | If not provided,it is calculated internally from rain when air temperature \< 0 degC |
| Sea level pressure | Pa | Sea_Level_Barometric_Pressure_pascal | Not required |
| Surface level pressure | Pa | Surface_Level_Barometric_Pressure_pascal | Required |
| Vapour pressure | mbar | Vapor_Pressure_milliBar | If not provided,it is calculated internally from air temperature and relative humidity/dewpoint temperature |
: Table 1. Description of meteorological variables used within LakeEnsemblR with units and required column names.

## Inflow data

The data needs to be a comma separated values (.csv) file where the datetime column is in the format
`YYYY-mm-dd HH:MM:SS`. See table 2 for the list of variables, units and column names. Providing
inflow data is optional.

| Description                      | Units | Column Name                                         | Status                                                                                                                                                            |
|----------------------------------|-------|-----------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Discharge volumetric flow rate  | m3/s  | Flow_metersCubedPerSecond  | Required |
| Water temperature | 째C  | Water_Temperature_celsius | Required         |       
| Salinity | PSU  | Salinity_practicalSalinityUnits | Required         |              
: Table 2. Description of inflow variables used within LakeEnsemblR with units and required column names.

## LakeEnsemblR YAML configuration file

There is an example yaml configuration provided in the example dataset in the package or you can
download a copy from GitHub
[here](https://github.com/aemon-j/LakeEnsemblR/blob/master/inst/extdata/feeagh/LakeEnsemblR.yaml).

You will need to update each of the required variables in the location block to reflect your own
site.

```         
location:
   name: Feeagh                                 # station name used in output [default=GOTM site]
   latitude: 53.9                               # latitude [degrees North; min=-90.0; max=90.0; default=0.0]
   longitude: -9.5                              # longitude [degrees East; min=-360.0; max=360.0; default=0.0]
   elevation: 15                                # elevation of lake surface above sea level [m]
   depth: 46.8                                  # maximum water depth [m; min=0.0; default=100.0]
   hypsograph: LakeEnsemblR_bathymetry_standard.csv                 # hypsograph [default=]
   init_depth: 46.8                             # initial height of lake surface relative to the bottom [m]
```

Then input the filepaths to the bathymetry, meteorlogical and water temperature profile observations
file. For first time users we would recommend to set up a folder with just these three files plus
the LakeEnsemblR yaml configuration file.

Now you should be ready to [run
LakeEnsemblR](https://github.com/aemon-j/LakeEnsemblR/wiki/3.-Running-LakeEnsemblR) on your site.
