#' Format inflow data for each model
#'@description
#' Format dataframe into shape for the specified model
#'
#' @name format_inflow
#' @param inflow dataframe; as read.csv() from standardised input.
#' @param model character; Model for which scaling parameters will be applied. Options include
#'    c('GOTM', 'GLM', 'Simstrat', 'FLake')
#' @param config_file filepath; To LER config yaml file. Only used if model = 'GOTM'
#' @param folder filepath; to folder which contains the model folders generated by export_config()
#' @return dataframe of met data in the model format
#' @export
format_inflow <- function(inflow, model, config_file, folder = "."){
  
  
  hyp_file <- get_yaml_value(config_file, "location", "hypsograph")
  if(!file.exists(hyp_file)){
    stop(hyp_file, " does not exist. Check filepath in ", config_file)
  }
  hyp <- read.csv(hyp_file)
  
  if("FLake" %in% model){
    
    flake_inflow <- inflow
    
    flake_inflow <- flake_inflow[, c("Flow_metersCubedPerSecond",
                                 "Water_Temperature_celsius")]
    
    colnames(flake_inflow) <- c("FLOW", "TEMP")
    
    flake_inflow[, 1] <- (flake_inflow[, 1]) / max(hyp$Area_meterSquared)
    
    #Reduce number of digits
    flake_inflow <- signif(flake_inflow, digits = 8)
    
    return(flake_inflow)
    
  }
  
  if("GLM" %in% model){
    
    glm_inflow <- inflow
    
    glm_inflow <- glm_inflow[, c("datetime", "Flow_metersCubedPerSecond",
                           "Water_Temperature_celsius",
                           "Salinity_practicalSalinityUnits")]
    
    colnames(glm_inflow) <- c("Time", "FLOW", "TEMP", "SALT")
    glm_inflow[, 1] <- format(glm_inflow[, 1], format = "%Y-%m-%d %H:%M:%S")
    
    #Reduce number of digits
    glm_inflow[, -1] <- signif(glm_inflow[, -1], digits = 8)
    
    return(glm_inflow)
  }
  
  if("GOTM" %in% model){
    
    gotm_inflow <- inflow
    
    gotm_inflow <- gotm_inflow[, c("datetime", "Flow_metersCubedPerSecond",
                                 "Water_Temperature_celsius",
                                 "Salinity_practicalSalinityUnits")]
    
    colnames(gotm_inflow)[1] <- paste0("!", colnames(gotm_inflow)[1])
    gotm_inflow[, 1] <- format(gotm_inflow[, 1], "%Y-%m-%d %H:%M:%S")
    
    #Reduce number of digits
    gotm_inflow[, -1] <- signif(gotm_inflow[, -1], digits = 8)
    
    return(gotm_inflow)
  }
  
  if("Simstrat" %in% model){
    
    simstrat_inflow <- inflow
    
    simstrat_inflow <- simstrat_inflow[, c("datetime", "Flow_metersCubedPerSecond",
                                   "Water_Temperature_celsius",
                                   "Salinity_practicalSalinityUnits")]
    
    simstrat_inflow[, 1] <- format(simstrat_inflow[, 1], "%Y-%m-%d %H:%M:%S")
    
    #Reduce number of digits
    simstrat_inflow[, -1] <- signif(simstrat_inflow[, -1], digits = 8)
    
    return(simstrat_inflow)
  }
  
  if("MyLake" %in% model) {
    
    mylake_inflow <- inflow
    
    mylake_inflow <- mylake_inflow[, c("datetime", "Flow_metersCubedPerSecond",
                                           "Water_Temperature_celsius",
                                           "Salinity_practicalSalinityUnits")]
    
    mylake_inflow$Flow_metersCubedPerDay <- mylake_inflow$Flow_metersCubedPerSecond * (86400.)
    
    mylake_inflow[, 1] <- format(mylake_inflow[, 1], "%Y-%m-%d %H:%M:%S")
    
    #Reduce number of digits
    mylake_inflow[, -1] <- signif(mylake_inflow[, -1], digits = 8)
    
    return(mylake_inflow)
  }
}


#' Format outflow data for each model
#'@description
#' Format dataframe into shape for the specified model
#'
#' @name format_outflow
#' @param outflow dataframe; as read.csv() from standardised input.
#' @param model character; Model for which scaling parameters will be applied. Options include
#'    c('GOTM', 'GLM', 'Simstrat', 'FLake')
#' @param config_file filepath; To LER config yaml file. Only used if model = 'GOTM'
#' @param folder filepath; to folder which contains the model folders generated by export_config()
#' @return dataframe of met data in the model format
#' @export
format_outflow <- function(outflow, model, config_file, folder = "."){
  
  
  if("FLake" %in% model){
    stop("FLake does not need outflows, as mass fluxes are not considered.")
  }
  
  if("GLM" %in% model){
    
    glm_outflow <- outflow
    
    glm_outflow <- glm_outflow[, c("datetime", "Flow_metersCubedPerSecond")]
    
    colnames(glm_outflow) <- c("Time", "FLOW")
    glm_outflow[, 1] <- format(glm_outflow[, 1], format = "%Y-%m-%d %H:%M:%S")
    
    #Reduce number of digits
    glm_outflow[, -1] <- signif(glm_outflow[, -1], digits = 8)
    
    return(glm_outflow)
  }
  
  if("GOTM" %in% model){
    
    gotm_outflow <- outflow
    
    gotm_outflow <- gotm_outflow[, c("datetime", "Flow_metersCubedPerSecond")]
    
    colnames(gotm_outflow)[1] <- paste0("!", colnames(gotm_outflow)[1])
    gotm_outflow[, 1] <- format(gotm_outflow[, 1], "%Y-%m-%d %H:%M:%S")
    
    #Reduce number of digits
    gotm_outflow[, -1] <- signif(gotm_outflow[, -1], digits = 8)
    
    return(gotm_outflow)
  }
  
  if("Simstrat" %in% model){
    
    simstrat_outflow <- outflow
    
    simstrat_outflow <- simstrat_outflow[, c("datetime", "Flow_metersCubedPerSecond")]
    
    simstrat_outflow[, 1] <- format(simstrat_outflow[, 1], "%Y-%m-%d %H:%M:%S")
    
    #Reduce number of digits
    simstrat_outflow[, -1] <- signif(simstrat_outflow[, -1], digits = 8)
    
    return(simstrat_outflow)
  }
  
  if("MyLake" %in% model) {
    stop("MyLake does not need specific outflows, as it employs automatic overflow.")
  }
}