#' Format meteorological data for each model
#'@description
#' Format dataframe into shape for the specified model
#'
#' @name scale_met
#' @param met dataframe; as read.csv() from standardised input.
#' @param model character; Model for which scaling parameters will be applied. Options include c('GOTM', 'GLM', 'Simstrat', 'FLake')
#' @param daily logical; Is the data on a daily timestep. Defaults to FALSE
#' @param config_file filepath; To LER config yaml file. Only used if model = 'GOTM'
#' @param folder filepath; to folder which contains the model folders generated by export_config()
#' @return dataframe of met data in the model format
#' @export
format_met <- function(met, model, daily = FALSE, config_file, folder = '.'){


  lat <- get_yaml_value(file = config_file, label = 'location', key = 'latitude')
  lon <- get_yaml_value(file = config_file, label = 'location', key = 'longitude')
  elev <- get_yaml_value(file = config_file, label = 'location', key = 'elevation')
  ### Naming conventions standard input
  # Depending on the setup of the standard config file, we can omit reading exact titles and read column numbers
  colname_time = "datetime"
  colname_wind_speed = "Ten_Meter_Elevation_Wind_Speed_meterPerSecond"
  colname_u_wind = "Uwind_meterPerSecond"
  colname_v_wind = "Vwind_meterPerSecond"
  colname_wind_direction = "Ten_Meter_Elevation_Wind_Direction_degree"
  colname_air_temperature = "Air_Temperature_celsius"
  colname_dewpoint_temperature = "Dewpoint_Temperature_celsius"
  colname_relative_humidity = "Relative_Humidity_percent"
  colname_solar_radiation = "Shortwave_Radiation_Downwelling_wattPerMeterSquared"
  colname_longwave_radiation = "Longwave_Radiation_Downwelling_wattPerMeterSquared"
  colname_surface_pressure = "Surface_Level_Barometric_Pressure_pascal"
  colname_precipitation = "Precipitation_meterPerSecond"
  colname_snow = "Snowfall_meterPerDay"
  colname_vapour_pressure = "Vapor_Pressure_milliBar"
  colname_cloud_cover = "Cloud_Cover_decimalFraction"

  ### Check what met data is available, as this determines what model forcing option to use (in the simstrat config file)
  datetime = colname_time %in% colnames(met)
  wind_speed = colname_wind_speed %in% colnames(met)
  u_wind = colname_u_wind %in% colnames(met)
  v_wind = colname_v_wind %in% colnames(met)
  wind_direction = colname_wind_direction %in% colnames(met)
  air_temperature = colname_air_temperature %in% colnames(met)
  dewpoint_temperature = colname_dewpoint_temperature %in% colnames(met)
  solar_radiation = colname_solar_radiation %in% colnames(met)
  vapour_pressure = colname_vapour_pressure %in% colnames(met)
  relative_humidity = colname_relative_humidity %in% colnames(met)
  longwave_radiation = colname_longwave_radiation %in% colnames(met)
  cloud_cover = colname_cloud_cover %in% colnames(met)
  # Availability of precipitation data only used for snow module
  precipitation = colname_precipitation %in% colnames(met)
  snowfall = colname_snow %in% colnames(met)
  heat_flux = FALSE


  # Calculate other required variables
  # Relative humidity
  if(!relative_humidity & air_temperature & dewpoint_temperature){
    # The function is in helpers.R the formula is from the weathermetrics package
    met[[colname_relative_humidity]] <- dewt2relh(met[[colname_dewpoint_temperature]], met[[colname_air_temperature]])
    if(is.na(sum(met[[colname_relative_humidity]]))){
      met[[colname_relative_humidity]] <- na.approx(met[[colname_relative_humidity]])
      message('Interpolated NAs')
    }
    relative_humidity <- TRUE
  }

  # Vapour pressure
  if(!vapour_pressure & relative_humidity){
    # Calculate vapour pressure as: relhum * saturated vapour pressure
    # Used formula for saturated vapour pressure from:
    # Woolway, R. I., Jones, I. D., Hamilton, D. P., Maberly, S. C., Muraoka, K., Read, J. S., . . . Winslow, L. A. (2015).
    # Automated calculation of surface energy fluxes with high-frequency lake buoy data.
    # Environmental Modelling & Software, 70, 191-198.

    met[[colname_vapour_pressure]]=met[[colname_relative_humidity]]/100 * 6.11 * exp(17.27 * met[[colname_air_temperature]] / (237.3 + met[[colname_air_temperature]]))
    vapour_pressure <- TRUE

  }

  # Cloud cover
  if(!cloud_cover){

    met[[colname_cloud_cover]] =  calc_cc(date = met$datetime,
                                          airt = met$Air_Temperature_celsius,
                                          relh = met$Relative_Humidity_percent,
                                          swr = met$Shortwave_Radiation_Downwelling_wattPerMeterSquared,
                                          lat = lat, lon = lon,
                                          elev = elev,
                                          daily = daily)
    cloud_cover <- TRUE

  }

  #Snowfall
  if(!snowfall){
    freez_ind <- which(met[[colname_air_temperature]] < 0)
    met[[colname_snow]] <- 0
    met[[colname_snow]][freez_ind] <- met[[colname_precipitation]][freez_ind]
    met[[colname_precipitation]][freez_ind] <- 0
    met[[colname_snow]] <- met[[colname_snow]] * 86400 # m s-1 to m d-1
    snowfall <- TRUE
  }
  # Precipitation
  # Precipitation needs to be in m h-1: 1 m s-1 = 3600 m h-1, or 1 m d-1 = 1/24 m h-1
  if(precipitation){
    met$`Precipitation_meterPerHour`=met[[colname_precipitation]]*3600
  }#else if(snowfall){
  #  met$`Precipitation_meterPerHour`=met[[colname_snow]]/24
  #}

  # Long-wave radiation
  if(!longwave_radiation & dewpoint_temperature){
    met[[colname_longwave_radiation]] <- calc_in_lwr(cc = met[[colname_cloud_cover]], airt = met[[colname_air_temperature]], dewt = met[[colname_dewpoint_temperature]])
  }else if(!longwave_radiation & !dewpoint_temperature & relative_humidity){
    met[[colname_longwave_radiation]] <- calc_in_lwr(cc = met[[colname_cloud_cover]], airt = met[[colname_air_temperature]], relh = met[[colname_relative_humidity]])
  }

  # wind speed
  if(!wind_speed & u_wind & v_wind){
    met[[colname_wind_speed]] <- sqrt(met[[colname_u_wind]]^2 + met[[colname_v_wind]]^2)
  }

  # wind direction
  if(!wind_direction & u_wind & v_wind){
    met[[colname_wind_direction]] = calc_windDir(met[[colname_u_wind]], met[[colname_v_wind]])
    wind_direction <- TRUE
  }

  # u and v wind vectors
  if(!u_wind & !v_wind & wind_speed & wind_direction){
    rads = met[[colname_wind_direction]]/180*pi
    met[[colname_u_wind]] = met[[colname_wind_speed]]*cos(rads)
    met[[colname_v_wind]] = met[[colname_wind_speed]]*sin(rads)
    u_wind <- TRUE
    v_wind <- TRUE
  }

  if(!u_wind & !v_wind & wind_speed & !wind_direction){
    met[[colname_u_wind]] = met[[colname_wind_speed]]
    met[[colname_v_wind]] = 0
    u_wind <- TRUE
    v_wind <- TRUE
  }


  if('FLake' %in% model){

    ## Extract start, stop, lat & lon for netCDF file from config file
    start <- get_yaml_value(config_file, "time", "start")
    stop <- get_yaml_value(config_file, "time", "stop")
    met_timestep <- get_yaml_value(config_file, "meteo", "time_step")
    fla_fil <- get_yaml_value(config_file, "config_files", "flake")
    fla_fil <- file.path(folder, fla_fil)


    # Subset temporally
    if(!is.null(start) & !is.null(stop)){
      fla_met <- met[(met[,1] >= start & met[,1] < stop),]
    }else{
      fla_met <- met
    }

    input_nml(fla_fil, label = 'SIMULATION_PARAMS', key = 'del_time_lk', met_timestep)


    fla_met$index <- 1:nrow(fla_met)

    # Re-organise
    fla_met <- fla_met[,c('index','Shortwave_Radiation_Downwelling_wattPerMeterSquared','Air_Temperature_celsius', "Vapor_Pressure_milliBar", "Ten_Meter_Elevation_Wind_Speed_meterPerSecond", "Cloud_Cover_decimalFraction", "datetime")]
    fla_met$datetime <- format(fla_met$datetime, format = '%Y-%m-%d %H:%M:%S')
    colnames(fla_met)[1] <- paste0('!', colnames(fla_met)[1])

    #Reduce number of digits
    fla_met[,-c(1, ncol(fla_met))] <- signif(fla_met[,-c(1, ncol(fla_met))], digits = 8)

    return(fla_met)
  }

  if('GLM' %in% model){

    glm_met <- met

    # Convert units
    glm_met$Precipitation_meterPerDay <- glm_met$Precipitation_meterPerSecond * 86400


    glm_met <- glm_met[,c('datetime','Shortwave_Radiation_Downwelling_wattPerMeterSquared', "Longwave_Radiation_Downwelling_wattPerMeterSquared", 'Air_Temperature_celsius', 'Relative_Humidity_percent', "Ten_Meter_Elevation_Wind_Speed_meterPerSecond", "Precipitation_meterPerDay", "Snowfall_meterPerDay")]

    colnames(glm_met) <- c('Date','ShortWave','LongWave','AirTemp','RelHum','WindSpeed','Rain','Snow')
    glm_met[,1] <- format(glm_met[,1], format = '%Y-%m-%d %H:%M:%S')

    #Reduce number of digits
    glm_met[,-1] <- signif(glm_met[,-1], digits = 8)

    return(glm_met)
  }

  if('GOTM' %in% model){

    got_met <- met

    lat <- get_yaml_value(file = config_file, label = 'location', key = 'latitude')
    lon <- get_yaml_value(file = config_file, label = 'location', key = 'longitude')
    elev <- get_yaml_value(file = config_file, label = 'location', key = 'elevation')



    got_met <- got_met[,c('datetime', 'Uwind_meterPerSecond', 'Vwind_meterPerSecond', 'Surface_Level_Barometric_Pressure_pascal', 'Air_Temperature_celsius', 'Relative_Humidity_percent', 'Cloud_Cover_decimalFraction', 'Shortwave_Radiation_Downwelling_wattPerMeterSquared', 'Precipitation_meterPerSecond')]

    colnames(got_met)[1] <- paste0('!', colnames(got_met)[1])
    got_met[,1] <- format(got_met[,1], '%Y-%m-%d %H:%M:%S')

    #Reduce number of digits
    got_met[,-1] <- signif(got_met[,-1], digits = 8)

    return(got_met)
  }

  if('Simstrat' %in% model){

    sim_met <- met

    par_file <- get_yaml_value(config_file, 'config_files', 'simstrat')
    par_file <- file.path(folder, par_file)

    # If snow_module is true, there needs to be a precipitation (or snowfall) columnn.
    if("Precipitation_meterPerHour" %in% colnames(sim_met)){
      snow_module = TRUE
      input_json(par_file, "ModelConfig", "SnowModel", 1)
    }else{
      snow_module = FALSE
      input_json(par_file, "ModelConfig", "SnowModel", 0)
    }

    ### Pre-processing
    # Time
    if('datetime' %in% colnames(sim_met)){
      # Time in simstrat is in decimal days since a defined start year
      start_year <- get_json_value(par_file, "Simulation", "Start year")

      sim_met$datetime = as.numeric(difftime(sim_met$datetime,as.POSIXct(paste0(start_year,"-01-01")),units = "days"))
    }else{
      stop("Cannot find \"datetime\" column in the input file. Without this column, the model cannot run")
    }

    # Determine forcing mode based on available met data
    if(datetime & u_wind & v_wind & air_temperature & solar_radiation & vapour_pressure & longwave_radiation){
      forcing_mode = 5
      sim_met = sim_met[, c(colname_time, colname_u_wind, colname_v_wind,
                            colname_air_temperature, colname_solar_radiation,
                            colname_vapour_pressure, colname_longwave_radiation)]
      if(snow_module){
        sim_met[["Precipitation_meterPerHour"]] = met[["Precipitation_meterPerHour"]]
      }

    }else if(datetime & u_wind & v_wind & heat_flux & solar_radiation){
      forcing_mode = 4
      stop('Simstrat: Forcing mode 4 currently not supported.')
    }else if(datetime & u_wind & v_wind & air_temperature & solar_radiation & vapour_pressure & cloud_cover){

      forcing_mode = 3
      sim_met = sim_met[, c(colname_time, colname_u_wind, colname_v_wind,
                            colname_air_temperature, colname_solar_radiation,
                            colname_vapour_pressure, colname_cloud_cover)]
      if(snow_module){
        sim_met[["Precipitation_meterPerHour"]] = met[["Precipitation_meterPerHour"]]
      }

    }else if(datetime & u_wind & v_wind & air_temperature & solar_radiation & vapour_pressure){
      forcing_mode = 2

      sim_met = sim_met[, c(colname_time, colname_u_wind, colname_v_wind,
                            colname_air_temperature, colname_solar_radiation,
                            colname_vapour_pressure)]
      if(snow_module){
        sim_met[["Precipitation_meterPerHour"]] = met[["Precipitation_meterPerHour"]]
      }

    }else if(datetime & u_wind & v_wind & air_temperature & solar_radiation){
      forcing_mode = 1
      sim_met = sim_met[, c(colname_time, colname_u_wind, colname_v_wind,
                            colname_air_temperature, colname_solar_radiation)]
      if(snow_module){
        sim_met[["Precipitation_meterPerHour"]] = met[["Precipitation_meterPerHour"]]
      }
    }else{
      stop(paste("Simstrat: There is not enough data to run the model in any forcing mode"))
    }

    # Set the forcing mode
    input_json(par_file, "ModelConfig", "Forcing", forcing_mode)

    #Reduce number of digits
    sim_met[,-1] <- signif(sim_met[,-1],8)

    return(sim_met)
  }
}
