#' Run Latin hypercube sampling in parallel
#' 
#' Call run_LHC with parallel::clusterApply
#' @param config_file filepath; to LakeEnsemblr yaml master config file
#' @param num integer; the number of random parameter sets to generate. If param file is provided
#' num = number of parameters in that file.
#' @param param_file filepath; to previously created parameter file set. If NULL creates a new
#' parameter set. Defaults to NULL
#' @param method character; Method for calibration. Can be "met", "model" or "both". Needs to be
#' specified by the user.
#' @param obs_file filepath; to LakeEnsemblR standardised observed water temperature profile data.
#' If included adds observed data to netCDF and list if they are set to TRUE. Defaults to NULL.
#' @param config_file filepath; to LakeEnsemblr yaml master config file
#' @param model vector; model to export driving data. Options include c("GOTM", "GLM", "Simstrat",
#' "FLake")
#' @param folder filepath; to folder which contains the model folders generated by export_config()
#' @param meteo_file filepath; to met file which is in the standardised LakeEnsemblR format.
#' @param folder filepath; to folder which contains the model folders generated by export_config()
#' @param spin_up numeric; Number of days to disregard as spin-up for analysis.
#'
#' @import parallel
#'
#' @export

run_LHC_parallel <- function(config_file, num = NULL, param_file = NULL, method,
                    model = c("FLake", "GLM", "GOTM", "Simstrat"), folder = ".",
                    spin_up = NULL, num_cores = NULL){
  if(is.null(num_cores)){
    num_cores <- detectCores()
  }
  
  if(length(model) < num_cores){
    cl <- makeCluster(length(model))
  }else{
    cl <- makeCluster(num_cores, outfile = 'calib_log.txt')
  }
  
  on.exit(stopCluster(cl))
  
  message("Starting parallel LHC: ", paste0("[", Sys.time(), "]"))
  # Run LHC in parallel
  clusterApply(cl = cl, x = model, fun = run_LHC, 
               config_file = config_file,
               num = num,
               param_file = param_file,
               method = method,
               folder = folder,
               spin_up = spin_up)
  message("Finished parallel LHC: ", paste0("[", Sys.time(), "]"))
  
  stopCluster(cl)
  
}