#' Run Ensemble of lake models
#'@description
#'Run each of the lake models
#'
#' @name run_ensemble
#' @param model vector; model to export driving data. Options include c('GOTM', 'GLM', 'Simstrat', 'FLake')
#' @param folder filepath; to folder which contains the model folders generated by export_config()
#' @param start character; Model start time in the format of 'YYYY-mm-dd HH:MM:SS
#' @param stop character; Model stop time in the format of 'YYYY-mm-dd HH:MM:SS
#' 
#' @example 
#' 
#' 
#' @export
run_ensemble <- function(model = c('GOTM', 'GLM', 'Simstrat', 'FLake'), folder = '.', start = NULL, stop = NULL){
  
  if('FLake' %in% model){
    #Need to figure out how to subset data by dates
    
    # Find nml file
    nml_file <- list.files(file.path(folder, 'FLake'))[grep('nml', list.files(file.path(folder, 'FLake')))]
    
    run_flake(sim_folder = file.path(folder, 'FLake'), nml_file = nml_file)
    message('FLake run is complete! ', paste0('[', Sys.time(),']'))
  }
  
  if('GLM' %in% model){
    #Need to input start and stop into nml file
    
    run_glm(sim_folder = file.path(folder, 'GLM'))
    
    message('GLM run is complete! ', paste0('[', Sys.time(),']'))
    
  }
  
  if('GOTM' %in% model){
    #Need to input start and stop into yaml file
    
    run_gotm(sim_folder = file.path(folder, 'GOTM'))
    
    message('GOTM run is complete! ', paste0('[', Sys.time(),']'))
    
  }
  
  if('Simstrat' %in% model){
    # Need to input start and stop into json par file
    
    fils <- list.files('Simstrat/')
    par_file <- fils[grep('par', fils)]
    
    run_simstrat(sim_folder = file.path(folder, 'Simstrat'), par_file = par_file)
    
    message('Simstrat run is complete! ', paste0('[', Sys.time(),']'))
    
  }
}